# Generated by Django 4.2.7 on 2023-11-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image_alt', models.CharField(max_length=255)),
                ('image_src', models.URLField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
