# Generated by Django 4.2.7 on 2023-11-29 03:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_src',
            field=models.ImageField(upload_to='blog-images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
