# Generated by Django 4.2.7 on 2023-11-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_text',
        ),
    ]
