# Generated by Django 4.2.7 on 2023-11-27 21:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
