# Generated by Django 4.2.7 on 2023-11-27 21:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
