# Generated by Django 4.2.7 on 2023-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_client_description_alter_service_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
