# Generated by Django 4.2.7 on 2023-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_service_title_alter_testimonial_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.CharField(default='', max_length=250),
        ),
    ]
