# Generated by Django 4.2.7 on 2023-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_client_name_alter_service_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='clients',
            field=models.ManyToManyField(to='about.client'),
        ),
        migrations.AddField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='about',
            name='services',
            field=models.ManyToManyField(to='about.service'),
        ),
        migrations.AddField(
            model_name='about',
            name='testimonial',
            field=models.ManyToManyField(to='about.testimonial'),
        ),
    ]
