# Generated by Django 4.2.7 on 2023-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_about_clients_about_is_active_about_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='testimonial',
            new_name='testimonials',
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(upload_to='client-images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(upload_to='service-images/'),
        ),
    ]
