# Generated by Django 4.2.7 on 2023-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('All', 'All'), ('Angular', 'Angular'), ('React', 'React'), ('JS', 'JS')], max_length=50)),
                ('imageUrl', models.URLField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterOptions', models.JSONField()),
                ('projects', models.ManyToManyField(to='portfolio.project')),
            ],
        ),
    ]
