# Generated by Django 4.2.7 on 2023-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_category_remove_project_category_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='filterOptions',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='filterOptions',
            field=models.ManyToManyField(to='portfolio.category'),
        ),
    ]
