# Generated by Django 4.2.7 on 2023-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
