# Generated by Django 4.2.7 on 2023-11-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_education_id_alter_experience_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
