# Generated by Django 4.2.7 on 2023-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_cv_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
